#!/bin/bash
current_dir=$(basename "$PWD")

if [[ "$current_dir" == "dev" ]]; then
    cd ..
fi

if [ -f "dev/environment" ]; then
    source dev/environment
else
    echo "warn: not found environment file, skip it..."
fi

cd mnt

cargo run