name: "Build Rust Application"
description: "Build Rust Application for release or debug"
inputs:
  release:
    description: "Build in release mode (default: false)"
    required: false
    default: "false"
  rust-toolchain:
    description: "Rust version to use"
    required: true
    default: "stable"
  github_token:
    description: "GitHub token"
    required: false
    default: ""

runs:
  using: "composite"
  steps:
    - name: Setup Rust toolchain
      uses: dtolnay/rust-toolchain@v1
      with:
        toolchain: ${{ inputs.rust-toolchain }}

    - name: Setup Rust Cache
      uses: Swatinem/rust-cache@v2
      with:
        cache-all-crates: true # 已设置，缓存 registry 源码
        cache-on-failure: true # 即使构建失败也保存缓存（调试时有用）
        sharedKey: my-workspace-cache # 可选：跨分支共享基础依赖（谨慎使用）
        workspaces: |
          . -> target

    - name: Download Maxmind
      uses: ./.github/actions/download-maxmind
      with:
        github_token: ${{ inputs.github_token }}

    - name: Build release
      uses: ./.github/actions/build
      with:
        release: true

    - name: Prepare release rust application
      shell: bash
      run: |
        ls ./builds >> /dev/null
        cp ./builds/gateway ./gateway/gateway

        ls ./dashboard/backend/

        mkdir ./dashboard/backend/run/
        mkdir ./dashboard/backend/run/assets/
        cp ./builds/dashboard ./dashboard/backend/run/dashboard
        cp ./builds/webgateway-mnt ./dashboard/backend/run/webgateway-mnt
        cp -r ./dashboard/backend/assets/* ./dashboard/backend/run/assets/

    - name: Build gateway and push Docker image
      uses: docker/build-push-action@v5
      with:
        context: ./gateway
        push: true
        tags: |
          ghcr.io/${{ github.repository }}/gateway:latest
          ghcr.io/${{ github.repository }}/gateway:${{ github.sha }}
          ghcr.io/${{ github.repository }}/gateway:${{ env.RELEASE_VERSION }}
        cache-from: type=gha
        cache-to: type=gha,mode=max

    - name: Build backend dashboard and push Docker image
      uses: docker/build-push-action@v5
      with:
        context: ./dashboard/backend
        push: true
        tags: |
          ghcr.io/${{ github.repository }}/dashboard-backend:latest
          ghcr.io/${{ github.repository }}/dashboard-backend:${{ github.sha }}
          ghcr.io/${{ github.repository }}/dashboard-backend:${{ env.RELEASE_VERSION }}
        cache-from: type=gha
        cache-to: type=gha,mode=max
