name: "Build Rust Application"
description: "Build Rust Application for release or debug"
inputs:
  release:
    description: "Build in release mode (default: false)"
    required: false
    default: "false"

runs:
  using: "composite"
  steps:
    - name: Build release
      uses: ./.github/actions/build
      with:
        release: true

    - name: Prepare release rust application
      shell: bash
      run: |
        ls ./builds
        cp ./builds/gateway ./gateway/gateway
        cp ./builds/dashboard ./dashboard/backend/dashboard
        cp ./builds/webgateway-mnt ./dashboard/backend/webgateway-mnt

    - name: Build gateway and push Docker image
      uses: docker/build-push-action@v5
      with:
        context: ./gateway
        push: true
        tags: |
          ghcr.io/${{ github.repository }}/gateway:latest
          ghcr.io/${{ github.repository }}/gateway:${{ github.sha }}
          ghcr.io/${{ github.repository }}/gateway:${{ env.RELEASE_VERSION }}
        cache-from: type=gha
        cache-to: type=gha,mode=max

    - name: Build backend dashboard and push Docker image
      uses: docker/build-push-action@v5
      with:
        context: ./dashboard/backend
        push: true
        tags: |
          ghcr.io/${{ github.repository }}/dashboard-backend:latest
          ghcr.io/${{ github.repository }}/dashboard-backend:${{ github.sha }}
          ghcr.io/${{ github.repository }}/dashboard-backend:${{ env.RELEASE_VERSION }}
        cache-from: type=gha
        cache-to: type=gha,mode=max
