name: "Build Dashboard Frontend"
description: "Build Dashboard Frontend for release or debug"

inputs:
  node-version: # 新增：Node.js 版本输入
    description: "Node.js version to use"
    required: false
    default: 24 # 默认使用 Node.js 20 LTS

runs:
  using: "composite"
  steps:
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: ${{ inputs.node-version }}

    - name: Enable Corepack (for Yarn)
      run: corepack enable
      shell: bash
    - name: Checkout repository
      uses: actions/checkout@v2

    # build it
    - name: Build and copy build artifacts
      shell: bash
      run: |
        cd dashboard/frontend
        yarn install
        yarn build

    - name: Upload artifacts
      uses: actions/upload-artifact@v4
      with:
        name: webgateway-dashboard-frontend
        path: dashboard/frontend/dist/*

    - name: Prepare frontend
      shell: bash
      run: |
        mkdir ./dashboard/frontend/run/dist
        ls ./dashboard/frontend/dist

        cp -r ./dashboard/frontend/dist/* ./dashboard/frontend/run/dist/
        ls ./dashboard/frontend/run/dist

    - name: Build frontend dashboard and push Docker image
      uses: docker/build-push-action@v5
      with:
        context: ./dashboard/frontend
        push: true
        tags: |
          ghcr.io/${{ github.repository }}/dashboard-frontend:latest
          ghcr.io/${{ github.repository }}/dashboard-frontend:${{ github.sha }}
          ghcr.io/${{ github.repository }}/dashboard-frontend:${{ env.RELEASE_VERSION }}
        cache-from: type=gha
        cache-to: type=gha,mode=max
