name: Build release
on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup toolchains
        uses: ./.github/actions/setup-toolchain
        with:
          rust-version: "stable"
          install-dependencies: "true"

      - name: Build release
        uses: ./.github/actions/build
        with:
          release: true
