name: Build release
on:
  push:
    branches:
      - master
    tags:
      - "v*"
  workflow_dispatch:

jobs:
  build-rust:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Setup environment
        uses: ./.github/actions/build-frontend

      - name: Build And Push Rust Application
        uses: ./.github/actions/build-rust

  build-frontend:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Setup environment
        uses: ./.github/actions/build-frontend

      - name: Build Frontend
        uses: ./.github/actions/build-frontend
