name: Build release
on:
  push:
    branches:
      - master
    tags:
      - "v*"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup toolchains
        uses: ./.github/actions/setup-toolchain
        with:
          rust-version: "stable"
          install-dependencies: "true"

      - name: Build release
        uses: ./.github/actions/build
        with:
          release: true

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
        context: ./gateway
        push: true
        tags: |
          ghcr.io/${{ github.repository }}/webgateway-gateway:latest
          ghcr.io/${{ github.repository }}/webgateway-gateway:${{ github.sha }}
          ghcr.io/${{ github.repository }}/webgateway-gateway:${{ github.ref }}
